### ISSUE TITLE
Optimize response to make it simpler?

### ISSUE THREAD

**Issue by NitroXenon** [andrewvy/league-node#3]
Today I tried `getCurrentGameByName`
But I got the following response :
http://pastebin.com/tsS4tSV4

I think that the response is too complicated. The response even gives me those useless keys array.

Also, in `getCurrentGameByName` api, the response only gives me the internal SummonerName but not the display name.

**Comment by NitroXenon** [comment]
Oh sorry I confused in JSON...
After watching [your example](https://github.com/andrewvy/node-lol-example) , I finally understand the structure of that response JSON.

Thx a lot.

Best regard,
Peter

**Comment by NitroXenon** [comment]
@andrewvy And now I know that it is impossible for `getCurrentGameByName` api to retrieve the display name of the summoner.

So I gonna build a MongoDB server to save the display name and internal name.

Finally, thank you for your great work on league-node project and I appreciate it a lot. Btw Garena servers don't have any open api. So the only way to get info in Garena servers is to use RTMP client/api. Hope you can update it if you have time :)

**Comment by andrewvy** [comment]
Great! I'm surprised it's working for you after a long period of inactivity, especially since Garena might have different implementations. :) Feel free to create any tickets you find.

I'm sure there's a lot of new stuff implemented that I haven't ported over to this library, so I'll probably find some things and port them over.

**Comment by NitroXenon** [comment]
@andrewvy [Here](https://github.com/NitroXenon/PVPNetConnect/blob/master/PublicMethods.cs) is the list of all the methods provided (written in C#). Hope this can helps you porting the new stuff. :)

**Comment by andrewvy** [comment]
Curious question, why are you using this node.js library over the C# one? :)

**Comment by NitroXenon** [comment]
It's because :
1. I want to learn more about node.js (back-end)
2. I can host node.js application on openshift/hheroku. They don't support .NET application
